title: THPT Analysis 2025
description: Nghiên cứu So sánh các Tổ hợp Môn THPT - Dự báo Điểm Chuẩn 2025
author: THPT Analysis Team
url: https://noiceboi.github.io/THPT_ANALYSIS_2025/

# GitHub Pages configuration - Use root index.html
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Build settings
markdown: kramdown
highlighter: rouge

# Exclude files from build
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - src/
  - config/
  - requirements.txt
  - setup.py
  - CONTRIBUTING.md
